//import scalariform.formatter.preferences._
//
//ScalariformKeys.preferences := ScalariformKeys.preferences.value
//  .setPreference(AlignParameters, true)
//  .setPreference(FormatXml, true)
//  .setPreference(PreserveDanglingCloseParenthesis, true)
//  .setPreference(SpaceInsideBrackets, false)
//  .setPreference(IndentWithTabs, false)
//  .setPreference(SpaceInsideParentheses, false)
//  .setPreference(MultilineScaladocCommentsStartOnFirstLine, false)
//  .setPreference(AlignSingleLineCaseStatements, true)
//  .setPreference(CompactStringConcatenation, false)
//  .setPreference(PlaceScaladocAsterisksBeneathSecondAsterisk, false)
//  .setPreference(IndentPackageBlocks, false)
//  .setPreference(CompactControlReadability, false)
//  .setPreference(SpacesWithinPatternBinders, true)
//  .setPreference(AlignSingleLineCaseStatements.MaxArrowIndent, 40)
//  .setPreference(DoubleIndentClassDeclaration, false)
//  .setPreference(PreserveSpaceBeforeArguments, false)
//  .setPreference(SpaceBeforeColon, false)
//  .setPreference(RewriteArrowSymbols, false)
//  .setPreference(IndentLocalDefs, false)
//  .setPreference(IndentSpaces, 2)
